name: Oracle Ampere Hunter

on:
  workflow_dispatch:

jobs:
  hunt:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    env:
      OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
      OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
      OCI_AD: ${{ secrets.OCI_AD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OCI CLI
        run: pip install oci-cli

      - name: Setup OCI Config
        run: |
          mkdir -p ~/.oci
          printf "%s" "${{ secrets.OCI_CONFIG }}" > ~/.oci/config
          printf "%s" "${{ secrets.OCI_KEY }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/config
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Run Hunter
        run: bash retry.sh